name: Build a Wokwi Custom Chip release and test it on Wokwi

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: [ubuntu-latest]
    container:
      # Use the Docker image as published in your GitHub Container Registry
      image: ghcr.io/${{ github.repository }}/ubuntu-24.04-with-tools:latest
    steps:
      # Install WASI sysroot. For now, we use our own install action.
      - name: Install WASI sysroot
        uses: phytol1515/wasi-sysroot-install-action@main
      - name: Debug WASI_SYSROOT
        run: echo ${WASI_SYSROOT}
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run CMake configure and build
        uses: lukka/run-cmake@v10
        with: 
          configurePreset: web-wasm-debug
          buildPreset: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chip-artifacts
          path: dist

  test:
    name: Test
    needs: build
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/${{ github.repository }}/ubuntu-24.04-with-tools:latest
    steps:
      - name: TBD
        run: |
          echo TBD

  release:
    name: Create Release (if tag pushed)
    # This job runs only when the ref is a tag
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: [ubuntu-latest]
    container:
      image: ghcr.io/${{ github.repository }}/ubuntu-24.04-with-tools:latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: chip-artifacts
      - name: Create a GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          updateOnlyUnreleased: true
          tag: ${{ github.ref_name }}
          # Attach the files as part of the release.
          artifacts: |
            dist/chip.wasm
            dist/chip.json

